alias: Wenn Wohnzimmertaster heller
description: ""
triggers:
  - domain: mqtt
    device_id: 04cd95a27a2b6cf0cd5d74dd29e14376
    type: action
    subtype: brightness_up_click
    trigger: device
conditions:
  - condition: state
    entity_id: light.wohnzimmerlampen
    state: "on"
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_step_pct: 10
    target:
      entity_id: light.wohnzimmerlampen
mode: single
